### ISSUE TITLE
Process is not alive

### ISSUE THREAD

**Issue by vinceurag** [era/pay#15]
Hello! I tried following the instructions the README file. I have no luck in making it work.

When I execute this command:
```
payment = %Paypal.Payment{
      intent: "sale",
      payer: %{"payment_method" => "paypal"},
      transactions: [%{"amount" => %{"currency" => "USD", "details" => %{"shipping" => "0.03", "subtotal" => "7.41", "tax" => "0.03"}, "total" => "7.47"}, "description" => "This is the payment transaction description."}],
      redirect_urls: %{"return_url" => "http://google.com", "cancel_url" => "http://google.com"}
    }
    Payment.create_payment(payment)
```

I receive this error:

```
[error] Task #PID<0.893.0> started from #PID<0.888.0> terminating
** (stop) exited in: GenServer.call(:token, {:get, #Function<2.36722068/1 in Paypal.Authentication.is_expired/0>}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:766: GenServer.call/3
    (pay) lib/paypal/authentication.ex:27: Paypal.Authentication.is_expired/0
    (pay) lib/paypal/authentication.ex:16: Paypal.Authentication.get_token/0
    (pay) lib/paypal/authentication.ex:60: Paypal.Authentication.authorization_header/0
    (pay) lib/paypal/authentication.ex:53: Paypal.Authentication.headers/0
    (pay) lib/paypal/payment.ex:42: Payment.Paypal.Payment.do_create_payment/1
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<0.63762606/0 in Payment.Paypal.Payment.create_payment/1>
    Args: []
[error] Ranch protocol #PID<0.888.0> (:cowboy_protocol) of listener KnvapiExWeb.Endpoint.HTTP terminated
** (exit) exited in: GenServer.call(:token, {:get, #Function<2.36722068/1 in Paypal.Authentication.is_expired/0>}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
```

Thanks!

**Comment by QwertyJack** [comment]
In your `application.ex` (maybe inside `$PROJECT_DIR/lib/` or so) add a ‘pay’ worker:
```
...
def start(_type, _args) do                                                                                
  import Supervisor.Spec
  ...
  children = [                                                                                                       
    ...                                                                           
    # Start your own worker by calling: Web.Worker.start_link(arg1, arg2, arg3)                                      
    worker(Pay, [_type, _args])                                                                                      
    ] 
...
```
Have fun !

**Comment by vinceurag** [comment]
For some reason, I forgot to say thanks a few years ago. It's better late than never :) thanks!
